spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/TiTravay}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:UserTest}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:aaa}
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.hibernate.ddl-auto=update
#springdoc.api-docs.path=/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.override-with-generic-response=false
spring.application.name=yneformaycheun
server.port=8080

spring.liquibase.enabled=false